services:
  postgres:
    image: postgres:17
    container_name: catalog-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    networks:
      - vintage-store-network

  mysql:
    image: mysql:8.4
    container_name: activity-db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=activitypwd
      - MYSQL_DATABASE=activitydb
    networks:
      - vintage-store-network

  mariadb:
    image: mariadb:10.11
    container_name: reviews-db
    ports:
      - "3307:3306"
    environment:
#      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=true
#      - MARIADB_USER=reviews
#      - MARIADB_PASSWORD=reviewspwd
#      - MARIADB_DATABASE=reviewsdb
      - MARIADB_ROOT_PASSWORD=reviewspwd
    networks:
      - vintage-store-network

networks:
  vintage-store-network:
    driver: bridge